all: idk

clean:
	find -not \( -name "*.*" -o -name "Makefile" \) -delete && find . -name "*.out" -type f -delete && find . -name "*.txt" -type f -delete

eclean:
	find -not \( -name "*.*" -o -name "Makefile" \) -delete && find . -name "*.out" -type f -delete && find . -name "*.txt" -type f -delete  && find . -name "*.in" -type f -delete 